### ISSUE TITLE
Very high ram usage

### ISSUE THREAD

**Issue by 4561235** [G-dH/gnome-colorblind-filters#3]
When tweaking the strength and toggling on/off the filter a lot of times the ram usage goes from 4GB to the max ram available (16GB on my pc). Disabling the extension does not free the ram.

Thank you for this extension it helps me a lot for my protanopia :)

**Comment by G-dH** [comment]
Thanks for the report, you're right. For some reason effect objects stay in the memory after removing all references to them. Unfortunately _Clutter.ShaderEffect_ doesn't support program updates, so every adjustment means removing the current effect and adding a new one. I can reduce the number of filter changes, but it's still unacceptable...

**Comment by G-dH** [comment]
I've found the solution, shaders are now less effective but with no memory leaks.

**Comment by G-dH** [comment]
The updated version is already on the EGO, so it should update automatically. However, using the strength slider may not affect the whole screen immediately, since all parts of the screen are not updated while the panel menu is opened. Re-enabling the effect would help, but there is the memory leak issue - even disabling/enabling the effect using its built-in _set_enable()_ function eats the memory, and sometimes the memory is freed after some time and sometimes not.

Let me know how that works for you.

**Comment by 4561235** [comment]
Thank you very much, I just tested and like you said now there is a need to toggle on/off after tweaking the strength to refresh the filter but it's not a big problem. The ram issue is gone and it works very well now, thanks again :D

**Comment by G-dH** [comment]
On my system (nvidia/X11) there is no need to toggle the effect on/off, closing the menu is enough. What is your graphics stack?

**Comment by 4561235** [comment]
Oh yes you are right closing the menu is enough I didn't noticed it :)

**Comment by G-dH** [comment]
Great, thanks for the feedback!
